app = "ksksksksksk-xqva7a"

primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"
  SESSION_NAME = "/app/data/my_personal_account"
  IMAGE_SOURCE = "pixabay"
  DOWNLOAD_DIR = "/app/profile_uploads"
  DELAY_BETWEEN_UPLOADS = "5.0"

[processes]
  app = "python main.py"

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 1

[[mounts]]
  source = "telegram_data"
  destination = "/app/data"
